version: '3.8'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: golf_club
    ports:
      - "3306:3306"
  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"